JSONAPIdotNET/JSONAPI.NET

JSONAPI.Tests/Json/JsonApiMediaFormaterTests.cs, JSONAPI/Json/JsonApiFormatter.cs
This PR allows serializing enum and nullable enum properties as primitive types. At the moment, the formatter treats them as linked resources, when they should probably be sent as integers instead.
=> serialize enums

JSONAPI.Tests/Json/JsonApiMediaFormaterTests.cs, JSONAPI/Json/JsonApiFormatter.cs
At the moment only generic enumerable types can be serialized as resource collections. This PR allows serializing arrays also.
=> serialize arrays

JSONAPI/Json/JsonApiFormatter.cs
This PR ensures that primitive-type properties that have a JsonIgnore attribute are not serialized. Previously, only navigation properties would be ignored if they had this attribute.
=> do not serialize primitive type properties that have a JsonIgnore attribute

JSONAPI/Json/JsonApiFormatter.cs
Small refactor to pave the way for being able to customize how to locate the ID property.
=> refactor GetIdFor

JSONAPI.Tests/Data/LinkTemplateTest.json, JSONAPI.Tests/JSONAPI.Tests.csproj, JSONAPI.Tests/Json/LinkTemplateTests.cs, JSONAPI/Json/JsonApiFormatter.cs
According to the spec, sending a link should look like this:
```
{
"posts": {
"id": "2",
"title": "How to fry an egg",
"links": {
"author": {
"href": "/users/5"
}
}
}
}
```
The formatter is currently sending:
```
{
"posts": {
"id": "2",
"title": "How to fry an egg",
"links": {
"author": "/users/5"
}
}
}
```
There is no way for the client to tell that that is a link and not an ID. This PR changes the handling for `[SerializeAs(SerializeAsOptions.Link)]` to put the link on an `href` key in an embedded object.
I needed the json minifier helper from #8, so I included it here as a separate commit. I may need to rebase one of these PRs when you merge the other.
=> Send link as href in embedded object

JSONAPI.Tests/ActionFilters/EnableFilteringAttributeTests.cs, JSONAPI.Tests/JSONAPI.Tests.csproj, JSONAPI/ActionFilters/EnableFilteringAttribute.cs, JSONAPI/JSONAPI.csproj
This adds a new action filter called JsonApiQueryableActionFilterAttribute that can be inserted into the WebAPI pipeline. It detects if the object content is an IQueryable<>. If it is, the filter performs exact-match filtering according to [the json-api spec](http://jsonapi.org/format/#fetching-filtering).
Filtering is supported for the following types:
* String
* Boolean
* SByte
* Byte
* Int16
* UInt16
* Int32
* UInt32
* Int64
* UInt64
* Single
* Double
* Decimal
* DateTime
* DateTimeOffset
* Enum
as well as their nullable counterparts. There is not yet support for linked IDs.
A few notes on the behavior:
* If multiple filter parameters are passed, they will be ANDed together. So `GET /people?firstName=John&lastName=Doe` will yield all people whose first name is John AND last name is …
=> Create webapi action filter for filtering IQueryables

JSONAPI.EntityFramework.Tests/EntityConverterTests.cs, JSONAPI.EntityFramework/EntityFrameworkMaterializer.cs, JSONAPI.EntityFramework/Http/ApiController.cs, JSONAPI/Core/IMaterializer.cs, JSONAPI/Http/ApiController.cs
=> add async method signatures to IMaterializer

JSONAPI/Json/JsonApiFormatter.cs
This is a PR against your PR #25. I think this is a better set of constructors. It isolates all the changes against the current class into one constructor, and I think it makes it clearer what exactly is going on. It also gives tests a more flexible interface for mocking dependencies.
I'm leaving the 2-param constructor internal for now, but we can open it up later if we decide to let users customize error serialization.
=> rearrange constructors

JSONAPI.Tests/Core/ModelManagerTests.cs, JSONAPI/Core/ModelManager.cs
If you try to call `ModelManager.GetJsonKeyForType()` for a single type, and then call it for an array of that same type, it will throw an error because it is trying to add to the cache a key that already exists.
=> fix bug in GetJsonKeyForType

JSONAPI.Tests/Data/DeserializeRawJsonTest.json, JSONAPI.Tests/Data/SerializerIntegrationTest.json, JSONAPI.Tests/JSONAPI.Tests.csproj, JSONAPI.Tests/Json/JsonApiMediaFormaterTests.cs, JSONAPI.Tests/Models/Comment.cs, JSONAPI/Attributes/SerializeStringAsRawJsonAttribute.cs, JSONAPI/JSONAPI.csproj, JSONAPI/Json/JsonApiFormatter.cs, JSONAPI/Json/JsonHelpers.cs
closes #34 
I took the opportunity to clean up that serializer integration test fixture file. The minification is now done inside the test, so if we need to modify the file, we won't go insane.
I also moved the minification utility into JSONAPI proper. The json sent from the client will now be minified during deserialization, before it reaches the ApiController. I could have gone either way on this one, but I felt that the format of the JSON during transit is no concern of the business layer. If it wants its JSON formatted in a certain way, it can deal with that itself after we are done with it.
=> allow serialization of embedded raw json

JSONAPI.Tests/ActionFilters/EnableFilteringAttributeTests.cs, JSONAPI/ActionFilters/EnableFilteringAttribute.cs
closes #14 
To get the model manager into the filter, I'm going with a constructor parameter for now. `IFilterProvider` is a bit tricky and I wanted to just get this feature working.
=> allow filtering by the id property on related resources

JSONAPI.Tests/Data/MalformedRawJsonString.json, JSONAPI.Tests/Data/ReformatsRawJsonStringWithUnquotedKeys.json, JSONAPI.Tests/JSONAPI.Tests.csproj, JSONAPI.Tests/Json/JsonApiMediaFormaterTests.cs, JSONAPI/Json/JsonApiFormatter.cs
I realized that my code that serializes raw JSON down from the database has no protections to ensure that the data is actually valid JSON. If it's malformed in any way, the formatter will happily send it onto the wire and the client will choke on the response.
I added a check that validates raw json properties before they are serialized. If the property value contains unparseable syntax, like `{ x }`, then the entire object will be sent down as an empty hash `{}`. If the property value contains unquoted keys, then the keys will be quoted. So `{ foo: 3 }` will be serialized as `{ "foo": 3 }`.
(I originally wanted to have the same behavior if we detect unquoted keys as if the JSON is malformed. But I don't think it's possible to make Json.NET do this - the JToken parser just converts the …
=> add safeguards against invalid raw json strings

JSONAPI.EntityFramework.Tests/EntityFrameworkMaterializerTests.cs, JSONAPI.EntityFramework.Tests/JSONAPI.EntityFramework.Tests.csproj, JSONAPI.EntityFramework.Tests/Models/Backlink.cs, JSONAPI.EntityFramework.Tests/Models/TestEntities.cs, JSONAPI.EntityFramework/EntityFrameworkMaterializer.cs, JSONAPI.EntityFramework/Properties/AssemblyInfo.cs
`GetKeyNames` was completely broken, actually: it was always returning only `Id`, and swallowing an exception on every run. Now it properly checks for several conditions, and has tests to back it up.
Also fixed `TestEntities` to be able to delete the DB and recreate the model if it changes (which it did in this commit).
=> EF materializer nonstandard id bug

JSONAPI.EntityFramework.Tests.TestWebApp/Models/User.cs, JSONAPI.EntityFramework.Tests.TestWebApp/Startup.cs, JSONAPI.EntityFramework.Tests/Acceptance/AcceptanceTestsBase.cs, JSONAPI.EntityFramework.Tests/Acceptance/Data/User.csv, JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Users_GetSortedAscendingResponse.json, JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Users_GetSortedByColumnMissingDirectionResponse.json, JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Users_GetSortedByMixedDirectionResponse.json, JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Users_GetSortedByMultipleAscendingResponse.json, JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Users_GetSortedByMultipleDescendingResponse.json, JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Users_GetSortedBySameColumnTwiceResponse.json, JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Users_GetSortedByUnknownColumnResponse.json, JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Users_GetSortedDescendingResponse.json, JSONAPI.EntityFramework.Tests/Acceptance/SortingTests.cs, JSONAPI.EntityFramework.Tests/Acceptance/UserGroupsTests.cs, JSONAPI.EntityFramework.Tests/JSONAPI.EntityFramework.Tests.csproj, JSONAPI.Tests/ActionFilters/EnableSortingAttributeTests.cs, JSONAPI.Tests/JSONAPI.Tests.csproj, JSONAPI.TodoMVC.API/Startup.cs, JSONAPI/ActionFilters/EnableSortingAttribute.cs, JSONAPI/JSONAPI.csproj
I implemented sorting as another action filter. Its OnActionExecuted needs to run after the filtering attribute (so it has to be placed before it in the config, due to nesting). This works according to the [new spec](https://github.com/dgeb/json-api/blob/v1rc2/format/index.md#sorting-), so it requires sort expressions to be prefixed with + or -.
Closes #17
=> Add sorting action filter

JSONAPI.Tests/Data/ErrorSerializerTest.json, JSONAPI.Tests/JSONAPI.Tests.csproj, JSONAPI.Tests/Json/ErrorSerializerTests.cs, JSONAPI.Tests/Json/JsonApiMediaFormaterTests.cs, JSONAPI.Tests/packages.config, JSONAPI/Json/ErrorSerializer.cs, JSONAPI/Properties/AssemblyInfo.cs
Closes #63 
This doesn't leave us any better off in terms of being able to log errors along with their ID, but at least now the inner exceptions will have an ID too...
=> ensure that inner exceptions are given an ID

JSONAPI/Json/JsonApiFormatter.cs
The `readStream` and `serializer` parameters weren't being used so I pruned them.
Also I don't believe `Deserialize` should be public. If we wind up leaving the JsonApiFormatter class public then this should warrant a breaking change mention in the 0.4.0 changelog.
=> cleanup formatter code a little

JSONAPI.EntityFramework.Tests/Acceptance/AcceptanceTestsBase.cs, JSONAPI/Json/JsonApiFormatter.cs
This PR ensures that:
* The Content-Type for responses is set to `application/vnd.api+json` by default.
* 400 errors set `application/vnd.api+json` instead of `text/html`.
=> ensure correct content-type is sent

JSONAPI.EntityFramework.Tests.TestWebApp/Controllers/CommentsController.cs, JSONAPI.EntityFramework.Tests.TestWebApp/Controllers/PostsController.cs, JSONAPI.EntityFramework.Tests.TestWebApp/Controllers/TagsController.cs, JSONAPI.EntityFramework.Tests.TestWebApp/Controllers/UserGroupsController.cs, JSONAPI.EntityFramework.Tests.TestWebApp/Controllers/UsersController.cs, JSONAPI.EntityFramework.Tests/EntityConverterTests.cs, JSONAPI.EntityFramework.Tests/EntityFrameworkMaterializerTests.cs, JSONAPI.EntityFramework/EntityFrameworkMaterializer.cs, JSONAPI.EntityFramework/Http/ApiController.cs, JSONAPI/Core/IMetadataManager.cs, JSONAPI/Core/MetadataManager.cs, JSONAPI/JSONAPI.csproj
This PR makes `MetadataManager` implement an `IMetadataManager` interface. `EntityFrameworkMaterializer` now takes an `IMetadataManager` constructor parameter. This is the first step towards being able to de-singleton-ize `MetadataManager`.
=> inject IMetadataManager onto EntityFrameworkMaterializer

JSONAPI.EntityFramework/EntityFrameworkMaterializer.cs, JSONAPI/Extensions/TypeExtensions.cs
This cuts a duplicated method in EFM--but requires making the `TypeExtensions` public. Probably not a problem?
Didn't add any tests because arguably they'd just be duplicates of those on `CanWriteAsJsonApiAttribute`...should I anyway?
=> Fixes EntityFrameworkMaterializer bugs when materializing Decimal, etc.

JSONAPI.EntityFramework.Tests.TestWebApp/Startup.cs, JSONAPI.EntityFramework.Tests/EntityConverterTests.cs, JSONAPI.Tests/ActionFilters/EnableSortingAttributeTests.cs, JSONAPI.Tests/Core/MetadataManagerTests.cs, JSONAPI.Tests/Core/ModelManagerTests.cs, JSONAPI.Tests/Json/JsonApiMediaFormatterTests.cs, JSONAPI.Tests/Json/LinkTemplateTests.cs, JSONAPI.TodoMVC.API/Startup.cs, JSONAPI/ActionFilters/EnableSortingAttribute.cs, JSONAPI/Core/IModelManager.cs, JSONAPI/Core/ModelManager.cs, JSONAPI/Json/JsonApiFormatter.cs
This PR paves the way for polymorphism (#73) and heterogeneous collection support by requiring the user to pre-register all resource types. This will be a major breaking change as existing apps will fail until they add their necessary registrations.
I changed the language of `GetJsonKeyForType` to `GetResouceTypeNameForType` because the spec no longer wants primary data to be keyed by type, but rather by the word `data`. "Resource type name" seemed a more apt description of what we are determining.
I also added a virtual method on `ModelManager` called `CalculateResourceTypeNameForType` which will allow sub-classes to override the default strategy for determining the resource type name.
@SphtKr do you have any concerns?
=> require registration of resource types

JSONAPI.EntityFramework.Tests/Acceptance/Fixtures/Heterogeneous/Responses/GetSearchResultsResponse.json, JSONAPI.Tests/ActionFilters/EnableFilteringAttributeTests.cs, JSONAPI.Tests/Core/MetadataManagerTests.cs, JSONAPI.Tests/Core/ModelManagerTests.cs, JSONAPI.Tests/Data/NonStandardIdTest.json, JSONAPI.Tests/Json/JsonApiMediaFormatterTests.cs, JSONAPI.Tests/Json/LinkTemplateTests.cs, JSONAPI/ActionFilters/EnableFilteringAttribute.cs, JSONAPI/ActionFilters/EnableSortingAttribute.cs, JSONAPI/Core/IModelManager.cs, JSONAPI/Core/ModelManager.cs, JSONAPI/Core/ModelProperty.cs, JSONAPI/JSONAPI.csproj, JSONAPI/Json/JsonApiFormatter.cs
Summary of changes:
1. `ModelManager` now discovers everything it needs to know about a type's properties when that type is registered, rather than when the type is first (de)serialized. Closes #82 
2. `GetProperties()` now returns a wrapper class for `PropertyInfo` called `ModelProperty`, which stores the `PropertyInfo` as well as the serialized json key and whether the property should be ignored by default in serialization. This class is abstract and has two child classes: `FieldModelProperty` and `RelationshipModelProperty`. The latter tracks the cardinality of the relationship as well as the related type.
3. `GetPropertyForJsonKey()` returns a `ModelProperty`.
4. `GetJsonKeyForProperty` is gone from `IModelManager`. Any code that was using this can use the field on `ModelProperty` …
=> Model manager changes

JSONAPI.Tests/ActionFilters/DefaultPaginationTransformerTests.cs, JSONAPI.Tests/JSONAPI.Tests.csproj, JSONAPI/ActionFilters/DefaultPaginationTransformer.cs, JSONAPI/ActionFilters/IQueryablePaginationTransformer.cs, JSONAPI/ActionFilters/JsonApiQueryableAttribute.cs, JSONAPI/Core/JsonApiConfiguration.cs, JSONAPI/JSONAPI.csproj
This adds partial support for the [pagination feature of json-api](http://jsonapi.org/format/#fetching-pagination). `JsonApiQueryableAttribute` now takes an `IQueryablePaginationTransformer` parameter which works similarly to the filtering and sorting transformers. `JsonApiQueryableAttribute` will call the `IQueryablePaginationTransformer`'s `ApplyPagination` method after sorting.
When using fluent configuration, the default `IQueryablePaginationTransformer` is provided as `DefaultPaginationTransformer`. This implementation performs pagination based on a customizable pair of query parameters, which default to "page[number]" and "page[size]". An option is also available to set a maximum page size. If the user wants to specify their own implementation they can do so using …
=> Add partial support for pagination

JSONAPI.EntityFramework.Tests/Acceptance/PostsTests.cs, JSONAPI.Tests/ActionFilters/DefaultFilteringTransformerTests.cs, JSONAPI/ActionFilters/DefaultFilteringTransformer.cs
The spec's new policy on filtering says that `GET /posts?title=foo` should now be `GET /posts?filter[title]=foo`.
=> Use filter query param for filtering

JSONAPI.Tests/ActionFilters/DefaultFilteringTransformerTests.cs, JSONAPI.Tests/Core/ResourceTypeRegistrarTests.cs, JSONAPI/Core/DecimalAttributeValueConverter.cs, JSONAPI/QueryableTransformers/DefaultFilteringTransformer.cs
Found a bug for the FilteringTransformer and the Value Converter for Decimals, doubles and singles. In some cultures, such as se-SE, the decimal point is formatted as a comma (,). I don't remember which spec is says so in but I'm pretty sure that URIs and JSON wants non-localized formatting on those.
Added some regression tests that you can test out (without my changes) to see it fail.
=> Adding globalization for decimal, double and single for conversion.

JSONAPI.Tests/Core/ResourceTypeRegistrarTests.cs, JSONAPI.Tests/Models/AttributeGrabBag.cs, JSONAPI/Core/ObjectComplexAttributeValueConverter.cs, JSONAPI/Core/ResourceTypeRegistrar.cs, JSONAPI/JSONAPI.csproj
Now you can do
```
public class MyDto
{
[SerializeAsComplex]
public SomeOtherClass MyOtherClass {get; set; }
}
public class SomeOtherClass
{
[JsonProperty("foo-bar")]
public string FooBar {get; set;}
}
```
=> support serializing complex attributes to types other than string

JSONAPI/Json/LinkFormatter.cs, JSONAPI/Json/RelationshipObjectFormatter.cs, JSONAPI/Json/ResourceCollectionDocumentFormatter.cs, JSONAPI/Json/ResourceObjectFormatter.cs, JSONAPI/Json/SingleResourceDocumentFormatter.cs
The JSONAPI.JSON formatting classes are good candidates for property injection because there are acceptable local defaults. This will make it easier to instantiate ad hoc formatters - no need to new() up 10 different objects.
=> allow property injection for formatters

JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/DocumentMaterializers/StarshipDocumentMaterializer.cs, JSONAPI.EntityFramework/Http/EntityFrameworkDocumentMaterializer.cs, JSONAPI/Http/IDocumentMaterializer.cs, JSONAPI/Http/JsonApiController.cs, JSONAPI/Http/MappedDocumentMaterializer.cs
On `IDocumentMaterializer`, `DeleteRecord` is the only method that does not accept an HttpRequestMessage parameter. For scenarios where you really need access to the the request in response to a DELETE, there is no other alternative. This is a breaking change, but it should be a relatively easy mechanical refactor.
=> add HttpRequestMessage to DeleteRecord handler

JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Data/Child.csv, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Data/Master.csv, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/FetchingResourcesTests.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/FetchingResources/Get_related_to_many_integer_key_response.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests.csproj, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.csproj, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Models/Child.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Models/Master.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Models/TestDbContext.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Startup.cs, JSONAPI/Core/ResourceTypeRegistrar.cs
This is a very simple and possibly not optimal fix to allow filtering with entities that have integer keys.
I've added a test case that demonstrates the problem so hopefully you can either use this fix or achieve the same effect another way
=> Fix to allow filtering to work with entities that have integer keys

JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/CreatingResourcesTests.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Data/PostID.csv, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Data/PostLongId.csv, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/DeletingResourcesTests.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/CreatingResources/Requests/PostID_with_client_provided_id_Request.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/CreatingResources/Requests/PostLongId_with_client_provided_id_Request.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/CreatingResources/Responses/PostID_with_client_provided_id_Response.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/CreatingResources/Responses/PostLongId_with_client_provided_id_Response.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/UpdatingResources/Requests/PatchWithAttributeUpdateRequestID.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/UpdatingResources/Requests/PatchWithAttributeUpdateRequestLongId.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/UpdatingResources/Responses/PatchWithAttributeUpdateResponseID.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/UpdatingResources/Responses/PatchWithAttributeUpdateResponseLongId.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests.csproj, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/UpdatingResourcesTests.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.csproj, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Models/PostID.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Models/PostLongId.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Models/TestDbContext.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Startup.cs, JSONAPI.EntityFramework.Tests/DbContextExtensionsTests.cs, JSONAPI.EntityFramework.Tests/JSONAPI.EntityFramework.Tests.csproj, JSONAPI.EntityFramework.Tests/Models/PostID.cs, JSONAPI.EntityFramework/EntityFrameworkResourceObjectMaterializer.cs, JSONAPI.EntityFramework/Http/EntityFrameworkDocumentMaterializer.cs, JSONAPI/Core/ResourceTypeRegistrar.cs, JSONAPI/Extensions/StringExtensions.cs
- allow ID to be in upper case (Oracle generates this by default in upper)
- allow the id be long or decimal (Oracle numbers are mapped to decimal)
Thanks for the nice lib! I'm looking forward to create some more pull requests. 
refs: #109 #100
=> Fix: for non string keys with some tests / allow uppercase id

JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/FetchingResourcesTests.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/FetchingResources/Get_related_to_many_include_external_response.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests.csproj, JSONAPI.EntityFramework/Http/EntityFrameworkToManyRelatedResourceDocumentMaterializer.cs
I found an error in my implementation of eager loading on `EntityFrameworkToManyRelatedResourceDocumentMaterializer` which unfortunately was not coverd by a test with a resource which is nor related to primary.
=> bugfix: includes (eager-loading) must be applied to related not to primary resource!

JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp.Tests/Fixtures/AttributeSerialization/Attributes_of_various_types_serialize_correctly.json, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Controllers/SamplesController.cs, JSONAPI.AcceptanceTests.EntityFrameworkTestWebApp/Models/Sample.cs, JSONAPI.Tests/Extensions/TypeExtensionsTests.cs, JSONAPI/Extensions/TypeExtensions.cs
This allows you to add JToken properties to your CLR resource types and have JSONAPI.NET serialize them as attributes. Previously the framework tried to treat them as relationships.
=> Treat JToken properties as primitive attributes for serialization
